### ISSUE TITLE
Token storage must be configured.

### ISSUE THREAD

**Issue by rajaamerkhan** [Payum/Payum#464]
Upon following the first guide, I got this error:
```
[2016-02-04 11:31:18] local.ERROR: exception 'LogicException' with message 'Token storage must be configured.' in C:\wamp\www\mysite\vendor\payum\core\Payum\Core\PayumBuilder.php:356
Stack trace:
#0 C:\wamp\www\mysite\vendor\payum\payum-laravel-package\src\Payum\LaravelPackage\PayumServiceProvider.php(89): Payum\Core\PayumBuilder->getPayum()
#1 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Container\Container.php(289): Payum\LaravelPackage\PayumServiceProvider->Payum\LaravelPackage\{closure}(Object(Illuminate\Foundation\Application))
#2 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Container\Container.php(735): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#3 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Container\Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#4 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('payum', Array)
#5 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(218): Illuminate\Foundation\Application->make('payum')
#6 C:\wamp\www\mysite\vendor\payum\payum-laravel-package\src\Payum\LaravelPackage\Controller\PayumController.php(17): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#7 C:\wamp\www\mysite\vendor\payum\payum-laravel-package\src\Payum\LaravelPackage\Controller\PayumController.php(17): Illuminate\Support\Facades\App::make('payum')
#8 C:\wamp\www\mysite\app\Http\Controllers\PayPalController.php(15): Payum\LaravelPackage\Controller\PayumController->getPayum()
#9 [internal function]: App\Http\Controllers\PayPalController->prepareExpressCheckout()
#10 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(76): call_user_func_array(Array, Array)
#11 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('prepareExpressC...', Array)
#12 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\PayPalController), Object(Illuminate\Routing\Route), 'prepareExpressC...')
#13 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\PayPalController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'prepareExpressC...')
#19 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'prepareExpressC...')
#20 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#21 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Router.php(703): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#37 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#47 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Router.php(705): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Router.php(678): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Router.php(654): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#54 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#56 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#57 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#60 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#64 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#65 C:\wamp\www\mysite\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#66 C:\wamp\www\mysite\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#67 {main}  
```

My bootstrap/start.php
```
App::resolving('payum.builder', function(\Payum\Core\PayumBuilder $payumBuilder) {
    $payumBuilder
            // this method registers filesystem storages, consider to change them to something more
            // sophisticated, like eloquent storage
            ->addDefaultStorages()
            ->addGateway('paypal_ec', [
                'factory' => 'paypal_express_checkout',
                'username' => 'paymendsfdi1.fodfdfnedfet',
                'password' => '123123',
                'signature' => '1231231-SZHeJVBcEdEc.TLZfWY2-VGR',
                'sandbox' => true
            ])
    ;
});

```

My app/Http/Controllers/PayPalController.php
```
namespace App\Http\Controllers;

use Payum\Core\Request\GetHumanStatus;
use Payum\LaravelPackage\Controller\PayumController;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class PayPalController extends PayumController {

    public function prepareExpressCheckout() {
        $storage = $this->getPayum()->getStorage('Payum\Core\Model\ArrayObject');

        $details = $storage->create();
        $details['PAYMENTREQUEST_0_CURRENCYCODE'] = 'USD';
        $details['PAYMENTREQUEST_0_AMT'] = 1.23;
        $storage->update($details);

        $captureToken = $this->getPayum()->getTokenFactory()->createCaptureToken('paypal_ec', $details, 'payment_done');

        return \Redirect::to($captureToken->getTargetUrl());
    }

    public function done($payum_token) {
        /** @var Request $request */
        $request = \App::make('request');
        $request->attributes->set('payum_token', $payum_token);

        $token = $this->getPayum()->getHttpRequestVerifier()->verify($request);
        $gateway = $this->getPayum()->getGateway($token->getGatewayName());

        $gateway->execute($status = new GetHumanStatus($token));

        return \Response::json(array(
                    'status' => $status->getValue(),
                    'details' => iterator_to_array($status->getFirstModel())
        ));
    }

}

```

I have created a simple route paypal and redirected it to PayPalController@prepareExpressCheckout

Can anyone please tell where I am doing it wrong?

Thanks

**Comment by rajaamerkhan** [comment]
Hi,

I solved this issue. I moved the start.php code to my app.php before return $app; and it looks something like this now:

```
$app->resolving('payum.builder', function(\Payum\Core\PayumBuilder $payumBuilder) {
    $payumBuilder
            // this method registers filesystem storages, consider to change them to something more
            // sophisticated, like eloquent storage
            ->addDefaultStorages()
            ->addGateway('paypal_ec', [
                'factory' => 'paypal_express_checkout',
                'username' => 'paymendsfdi1.fodfdfnedfet',
                'password' => '123123',
                'signature' => '1231231-SZHeJVBcEdEc.TLZfWY2-VGR',
                'sandbox' => true
            ])
    ;
});
```
