### ISSUE TITLE
Unable to capture payment, vague error

### ISSUE THREAD

**Issue by KRens** [Payum/Payum#898]
Using stripe_checkout, I'm getting following vague error. It doesn't really tell me what to look into next in order to get this solved.

Fatal error: Uncaught Payum\Core\Reply\HttpResponse in /home/bot/domains/domain.com/public_html/payum/vendor/payum/stripe/Payum/Stripe/Action/Api/ObtainTokenAction.php:90 Stack trace: #0 /home/bot/domains/domain.com/public_html/payum/vendor/payum/core/Payum/Core/Gateway.php(107): Payum\Stripe\Action\Api\ObtainTokenAction->execute(Object(Payum\Stripe\Request\Api\ObtainToken)) #1 /home/bot/domains/domain.com/public_html/payum/vendor/payum/stripe/Payum/Stripe/Action/CaptureAction.php(38): Payum\Core\Gateway->execute(Object(Payum\Stripe\Request\Api\ObtainToken)) #2 /home/bot/domains/domain.com/public_html/payum/vendor/payum/core/Payum/Core/Gateway.php(107): Payum\Stripe\Action\CaptureAction->execute(Object(Payum\Core\Request\Capture)) #3 /home/bot/domains/domain.com/public_html/payum/vendor/payum/core/Payum/Core/Action/CapturePaymentAction.php(40): Payum\Core\Gateway->execute(Object(Payum\Core\Request\Capture)) #4 /home/bot/domains/domain.com/public_html/payum/ in /home/bot/domains/domain.com/public_html/payum/capture.php on line 20

**Comment by KRens** [comment]
Instead of using composer (this was breaking redirects) I download the entire zip file, but still I'm getting this error. Seems like fully broken.

**Comment by pierredup** [comment]
@KRens Can you please add your config files here to create a reproducer? (E.G paste the contents of your `capture.php`, `config.php` etc in order to see the full config and reproduce the error).
